=== Shiminmandy/Java_Part2/out/production/xml/plan.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT plan (course+)>
<!ELEMENT course (name,hour,exam-form)>
<!ATTLIST course id CDATA "">
<!ELEMENT name (#PCDATA)>
<!ELEMENT hour (#PCDATA)>
<!ELEMENT exam-form (#PCDATA)>

=== Shiminmandy/Java_Part2/out/production/xml/plan.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plan SYSTEM "plan.dtd"><!--教学计划teaching-plan--><!--练习dtd插入-->
<plan>
    <course id="001">
        <name>大学英语</name>
        <hour>36</hour>
        <exam-form>考试</exam-form>
    </course>
    <course id="002">
        <name>高等数学</name>
        <hour>70</hour>
        <exam-form>考试</exam-form>
    </course>
    <course id="003">
        <name>计算机应用基础</name>
        <hour>108</hour>
        <exam-form>上机考试</exam-form>
    </course>


    <course id="004">
        <name>大学物理</name>
        <hour>60</hour>
        <exam-form>考试</exam-form>
    </course>
</plan>
